import type { Metadata } from 'next';
import { EditorialShell, EditorialHero, EditorialLink, SectionLabel, StitchArtwork, whatsappLink } from '@/components/TonyEditorial';
import { TechniqueGuide } from '@/components/EditorialTools';
export const metadata: Metadata = { title:'Calidad, técnicas y acabados', description:'Conoce técnicas de personalización, telas, confección y acabados de Tony. Prepara las decisiones de tu uniforme con una guía clara.' };
export default function QualityPage() {
  return <EditorialShell className="te-quality"><EditorialHero label="Calidad" eyebrow="EL DETALLE TAMBIÉN JUEGA" title={<>Lo que se ve.<br /><em>Lo que se siente.</em></>} description="La identidad empieza en el diseño y se completa en la prenda. Conoce las decisiones que dan forma a tu uniforme: tela, confección y personalización." aside={<StitchArtwork />} />
    <section className="te-wrap te-rule"><SectionLabel number="01">Técnicas de personalización</SectionLabel><div className="te-section-heading"><h2>Una idea.<br /><em>Distintas formas de llevarla.</em></h2><p>Explora cada técnica para preparar tu propuesta. Su aplicación se confirma según la tela, el diseño y la prenda.</p></div><TechniqueGuide /></section>
    <section className="te-cream"><div className="te-wrap"><SectionLabel number="02">Construir la prenda</SectionLabel><h2>El diseño importa.<br /><em>La base, también.</em></h2><div className="te-material-grid"><article><span>01</span><h3>La tela.</h3><p>Compara textura, peso y sensación con una muestra antes de decidir. Tony publica líneas como Slim-Fit, Slim-Pro, Modern Carving, Dry-Fit, Premier, Dry-Cool, Dex-Air y Suplex.</p><ul><li>Textura</li><li>Sensación</li><li>Uso previsto</li></ul></article><article><span>02</span><h3>El molde.</h3><p>Define cómo quieres que quede la prenda y revisa la talla dentro de ese molde. Un corte ajustado y uno más amplio no se eligen solo por la letra de la etiqueta.</p><ul><li>Hombre</li><li>Mujer</li><li>Equipo mixto</li></ul></article><article><span>03</span><h3>Los detalles.</h3><p>Cuello, manga, costuras y acabados forman parte de la propuesta. En el pedido puedes indicar tus preferencias y revisarlas con Tony antes de producir.</p><ul><li>Cuello</li><li>Manga</li><li>Acabado</li></ul></article></div><p className="te-body-copy" style={{marginTop:28,color:'#49613d'}}>Las líneas publicadas no implican disponibilidad para todas las combinaciones. <a className="te-text-link" href="https://www.tonysportselsalvador.com/categoria/lineas-de-tela/" target="_blank" rel="noopener noreferrer">Explorar las telas publicadas por Tony <span aria-hidden="true">↗</span></a></p></div></section>
    <section className="te-wrap"><div className="te-intro-grid"><div><SectionLabel number="03">Acabados con identidad</SectionLabel><h2>Detalles que<br /><em>hablan de tu equipo.</em></h2><p className="te-body-copy">El acabado se elige por el diseño y por cómo quieres que se vea y se sienta. Consulta su viabilidad antes de cerrar tu propuesta.</p></div><div className="te-accordion"><details><summary>Costura Reinforced</summary><p>Tony describe esta costura como una unión plana con acabado limpio. Consulta en qué prendas y combinaciones está disponible. <a href="https://www.tonysportselsalvador.com/producto/costura-reinforced/" target="_blank" rel="noopener noreferrer">Ver el acabado publicado ↗</a></p></details><details><summary>Vinil textil</summary><p>La ficha de Tony presenta una aplicación de textura suave y relieve para logos o marcas. El tamaño y la tela se revisan para definir el acabado. <a href="https://www.tonysportselsalvador.com/producto/vinyl-textil/" target="_blank" rel="noopener noreferrer">Ver la referencia oficial ↗</a></p></details><details><summary>Logos 3D de alto relieve</summary><p>Tony publica logos existentes o personalizados con relieve e impresión a color. Comparte tu escudo y consulta qué detalles pueden reproducirse; el editor es una orientación visual. <a href="https://www.tonysportselsalvador.com/producto/logos-3d-alto-relieve/" target="_blank" rel="noopener noreferrer">Consultar el acabado 3D ↗</a></p></details></div></div></section>
    <section className="te-wrap te-rule"><div className="te-size-guide"><div><SectionLabel number="04">Elegir talla</SectionLabel><h2>Una talla para<br /><em>cada jugador.</em></h2><p>La nómina guarda la talla individual. Antes de confirmarla, pide la guía o una muestra correspondiente a la prenda y al molde elegidos.</p><div className="te-actions"><EditorialLink href={whatsappLink('Hola, Tony. Quiero consultar la guía de tallas y las medidas del molde para el uniforme de mi equipo.')} external>Consultar guía de tallas</EditorialLink></div></div><div className="te-accordion"><details open><summary>¿Por qué no elegir solo por la talla habitual?</summary><p>La misma etiqueta puede corresponder a diferentes medidas según la prenda y el molde. Confirma el ajuste esperado antes de asignar la talla a cada persona.</p></details><details><summary>¿Qué información conviene comparar?</summary><ul><li>Ancho de una prenda que te quede bien, extendida sin estirar.</li><li>Largo de la prenda y tipo de ajuste que prefieres.</li><li>La guía específica que Tony confirme para tu modelo.</li></ul></details><details><summary>¿Cómo organizar las tallas del equipo?</summary><p>Anota un nombre, una talla y un dorsal por uniforme. Revisa esa lista con cada jugador, incluidos los porteros, antes de compartir el pedido.</p></details></div></div></section>
  </EditorialShell>;
}
