import SectionImage from '@/components/SectionImage';
import type { Metadata } from 'next';
import stores from '@/data/tony-stores.json';
import { DeliveryBranchContact } from '@/components/EditorialTools';
import { EditorialShell, EditorialHero, EditorialLink, SectionLabel, SourceNote } from '@/components/TonyEditorial';
export const metadata: Metadata = {title:'Pedidos y entregas',description:'Conoce los pasos para cotizar, revisar el arte y coordinar la entrega de tu pedido Tony en El Salvador.'};
export default function DeliveryPage() {
  return <EditorialShell className="te-deliveries"><EditorialHero label="Entregas" eyebrow="CADA PASO, BIEN COORDINADO" title={<>De tu idea<br /><em>a tu equipo.</em></>} description="Un pedido claro empieza antes de producir y termina con una entrega coordinada. Aquí tienes lo necesario para conversar con Tony." aside={<div className="te-delivery-graphic"><SectionImage photo="entregas" shade="left" /><div><span>01 / PREPARAR</span>Tu equipo, completo.</div><div><span>02 / CONFIRMAR</span>Tu diseño, aprobado.</div><div><span>03 / COORDINAR</span>Tu entrega, acordada.</div></div>} />
    <section className="te-cream"><div className="te-wrap"><SectionLabel number="01">El recorrido del pedido</SectionLabel><h2>Primero los detalles.<br /><em>Después, la producción.</em></h2><div className="te-journey">{[{n:'01',title:'Preparar la solicitud',body:'Define la cantidad y la línea de prenda. Agrega un nombre, talla y dorsal por jugador y reúne tus imágenes.',note:'El editor genera una propuesta orientativa.'},{n:'02',title:'Recibir la cotización',body:'Comparte la solicitud con Tony para revisar materiales, personalización, costo y condiciones del pedido.',note:'La solicitud no confirma precio ni producción.'},{n:'03',title:'Aprobar los detalles',body:'Revisa el arte, la nómina y las características de la prenda. Aclara cualquier ajuste antes de autorizar el trabajo.',note:'Cuida nombres, números, tallas y colores.'},{n:'04',title:'Coordinar la entrega',body:'Acuerda con el asesor el destino, la persona que recibe y la fecha que corresponde a tu pedido.',note:'El costo y el plazo se confirman de forma directa.'}].map(step => <article key={step.n}><span>{step.n}</span><h3>{step.title}</h3><p>{step.body}</p><small>{step.note}</small></article>)}</div></div></section>
    <section className="te-wrap"><SectionLabel number="02">Cómo recibir tu pedido</SectionLabel><div className="te-delivery-options"><article className="te-delivery-option"><span>01 / A DOMICILIO</span><h3>Tu destino,<br /><em>tu sucursal.</em></h3><p>Coordina directamente con una sucursal cercana. Comparte tu municipio o zona para consultar las condiciones de la entrega.</p><DeliveryBranchContact stores={stores} /></article><article className="te-delivery-option"><span>02 / EN TIENDA</span><h3>Coordina<br /><em>tu visita.</em></h3><p>Si prefieres recibir atención en una tienda, consulta primero con el asesor dónde y cuándo puede coordinarse tu pedido. Evita trasladarte sin confirmación.</p><EditorialLink href="/tiendas" outline>Encontrar una tienda</EditorialLink></article></div><SourceNote href="https://www.tonysportselsalvador.com/servicio-a-domicilio/">Tony publica servicio a domicilio en El Salvador. Confirma las condiciones con la sucursal que elegiste.</SourceNote></section>
  </EditorialShell>;
}
