'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useRef,useState} from 'react';
import Brand from './Brand';
import CartLink from './CartLink';
import Icon from './Icon';
import {company,customer,SITE_DIRECTORY as searchEntries} from '@/lib/site-directory';
import {PRODUCT_CATEGORIES,productHref} from '@/lib/products';
import './site-navigation.css';

type Panel='product'|'company'|'customer';
const menus:{id:Panel;label:string}[]=[{id:'product',label:'Producto'},{id:'company',label:'Somos Tony'},{id:'customer',label:'Para ti'}];
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function Claw(){return <svg className="tony-nav-claw" viewBox="0 0 19 19" fill="none" aria-hidden="true"><path d="m7 2-4 15M12 2 8 17M17 2l-4 15" stroke="currentColor" strokeWidth="2"/></svg>}

export default function Header(){
  const path=usePathname(),isHome=path==='/';
  const header=useRef<HTMLElement>(null),panels=useRef<Partial<Record<Panel,HTMLDivElement>>>({});
  const mobile=useRef<HTMLDialogElement>(null),search=useRef<HTMLDialogElement>(null),menuButton=useRef<HTMLButtonElement>(null),searchButton=useRef<HTMLButtonElement>(null),searchInput=useRef<HTMLInputElement>(null);
  const [panel,setPanel]=useState<Panel|null>(null),[mobileOpen,setMobileOpen]=useState(false),[searchOpen,setSearchOpen]=useState(false),[accordion,setAccordion]=useState<Panel|null>(null),[query,setQuery]=useState(''),[top,setTop]=useState(118),[keyboard,setKeyboard]=useState(false);
  const active=(id:Panel)=>id==='product'?['/producto','/lineas','/catalogo','/colecciones'].includes(path):(id==='company'?company:customer).some(([href])=>path===href);
  function closePanels(){Object.values(panels.current).forEach(element=>{if(element?.matches(':popover-open'))element.hidePopover();});setPanel(null);}
  function closeMobile(){mobile.current?.close();setMobileOpen(false);}
  function closeSearch(){search.current?.close();setSearchOpen(false);}
  useEffect(()=>{closePanels();closeMobile();closeSearch();},[path]);
  useEffect(()=>{const replay=()=>{closePanels();closeMobile();closeSearch();};window.addEventListener('tony:intro-replay',replay);return()=>window.removeEventListener('tony:intro-replay',replay);},[]);
  useEffect(()=>{let frame=0;const update=()=>{if(innerWidth>=1200&&mobile.current?.open)closeMobile();if(innerWidth<1200&&panel)closePanels();if(panel)setTop(Math.round(header.current?.getBoundingClientRect().bottom??86));};const schedule=()=>{if(!frame)frame=requestAnimationFrame(()=>{frame=0;update();});};addEventListener('resize',schedule);if(panel)addEventListener('scroll',schedule,{passive:true});return()=>{cancelAnimationFrame(frame);removeEventListener('resize',schedule);removeEventListener('scroll',schedule);};},[panel]);
  function openPanel(which:Panel,fromKeyboard=false){setKeyboard(fromKeyboard);setTop(Math.round(header.current?.getBoundingClientRect().bottom??86));const element=panels.current[which];if(!element)return;if(element.matches(':popover-open'))element.hidePopover();else{closePanels();element.showPopover();if(fromKeyboard)requestAnimationFrame(()=>element.querySelector<HTMLAnchorElement>('a')?.focus());}}
  function openSearch(){closePanels();closeMobile();setSearchOpen(true);search.current?.showModal();searchInput.current?.focus();}
  const words=normalize(query).trim().split(/\s+/).filter(Boolean),availableEntries=searchEntries;
  const results=words.length?availableEntries.filter(item=>words.every(word=>normalize(`${item.label} ${item.terms} ${item.group}`).includes(word))):availableEntries;
  return <>
    <div className="tony-utility"><span><i aria-hidden="true"/> EL SALVADOR ES NUESTRA CANCHA.</span><div><Link href="/tiendas">Encuentra tu tienda</Link><Link href="/entregas">Entregas</Link><Link href="/contacto">Hablemos <Icon name="diagonal"/></Link></div></div>
    <header ref={header} className="site-header tony-header" onKeyDownCapture={event=>{if(event.key==='Escape'&&panel){event.preventDefault();const trigger=header.current?.querySelector<HTMLButtonElement>(`button[aria-controls="tony-${panel}-menu"]`);closePanels();trigger?.focus();}}} onBlur={event=>{if(panel&&!event.currentTarget.contains(event.relatedTarget as Node|null))closePanels();}}>
      <div className="tony-header-inner"><Brand/><nav className="tony-nav" aria-label="Navegación principal"><Link href="/" aria-current={isHome?'page':undefined}><Claw/>Inicio</Link>{menus.map(menu=><button key={menu.id} type="button" popoverTarget={`tony-${menu.id}-menu`} aria-expanded={panel===menu.id} aria-controls={`tony-${menu.id}-menu`} className={active(menu.id)?'is-current':''} onClick={event=>{event.preventDefault();openPanel(menu.id,event.detail===0);}} onKeyDown={event=>{if(event.key==='ArrowDown'){event.preventDefault();openPanel(menu.id,true);}}}><Claw/>{menu.label}<span className="tony-nav-plus" aria-hidden="true">{panel===menu.id?'−':'+'}</span></button>)}<Link href="/tony-news" aria-current={path==='/tony-news'?'page':undefined}><Claw/>Tony News</Link></nav><div className="tony-header-actions"><button ref={searchButton} type="button" className="tony-icon-button" aria-label="Buscar en el sitio" onClick={openSearch}><Icon name="search"/></button><CartLink/>{isHome&&<Link className="tony-header-cta" href="/configurador">CREA TU UNIFORME <span><Icon name="diagonal"/></span></Link>}<button ref={menuButton} type="button" className="tony-icon-button tony-menu-toggle" aria-label="Abrir menú" aria-controls="tony-mobile-menu" aria-expanded={mobileOpen} onClick={()=>{closePanels();setMobileOpen(true);mobile.current?.showModal();}}><Icon name="menu"/><span className="tony-menu-label">Menú</span></button></div></div>
      {menus.map(menu=><div id={`tony-${menu.id}-menu`} key={menu.id} ref={element=>{if(element)panels.current[menu.id]=element;else delete panels.current[menu.id];}} popover="auto" className={`tony-mega tony-mega-${menu.id}`} data-keyboard={keyboard} style={{top}} onToggle={event=>setPanel(event.currentTarget.matches(':popover-open')?menu.id:current=>current===menu.id?null:current)} aria-label={menu.label}>
        {menu.id==='product'?<div className="tony-product-menu"><div className="tony-world-manifesto"><span className="tony-mega-kicker">DE LA CANCHA A TU EMPRESA.</span><strong>LA IDENTIDAD<br/><em>SE VISTE.</em></strong><p>Explora nuestras líneas, opciones de confección y complementos.</p><Link href="/producto" onClick={closePanels}>Explorar Producto <Icon name="diagonal"/></Link><Claw/></div><div className="tony-product-menu-links">{PRODUCT_CATEGORIES.map((category,index)=><Link href={productHref(category)} key={category.id} onClick={closePanels}><span>{String(index+1).padStart(2,'0')}</span><strong>{category.shortLabel}</strong><Icon name="diagonal"/></Link>)}</div><div className="tony-product-menu-foot"><Link href="/calidad" onClick={closePanels}>Técnicas y acabados <Icon name="diagonal"/></Link><Link href="/catalogo" onClick={closePanels}>Catálogo y diseños <Icon name="diagonal"/></Link></div></div>:<div className={`tony-info-menu tony-info-${menu.id}`}><div className="tony-world-manifesto"><span className="tony-mega-kicker">{menu.id==='company'?'DE EL SALVADOR, CON IDENTIDAD.':'TE ACOMPAÑAMOS EN CADA PASO.'}</span><strong>{menu.id==='company'?<>MÁS QUE<br/>UNA <em>CAMISA.</em></>:<>CERCA DE TI.<br/><em>DE VERDAD.</em></>}</strong><p>{menu.id==='company'?'Personas, una historia y una misma pasión. Así somos Tony.':'La información que necesitas, justo cuando la necesitas.'}</p><Link href={menu.id==='company'?'/nosotros':'/contacto'} onClick={closePanels}>{menu.id==='company'?'Conoce a Tony':'Habla con nosotros'} <Icon name="diagonal"/></Link><Claw/></div><div className="tony-world-links">{(menu.id==='company'?company:customer).map(([href,label,description],index)=><Link href={href} key={href} onClick={closePanels}><span>{String(index+1).padStart(2,'0')}</span><div><strong>{label}</strong><small>{description}</small></div><Icon name="diagonal"/></Link>)}</div></div>}
      </div>)}
    </header>
    <nav className="tony-quick-directory" aria-label="Accesos rápidos"><button type="button" onClick={openSearch}><Icon name="search"/><span>¿Qué buscas en específico?</span></button><a href="#contactos">Contactos <Icon name="diagonal"/></a><Link href="/cuenta">Mi cuenta <Icon name="diagonal"/></Link></nav>
    <dialog ref={mobile} id="tony-mobile-menu" className="tony-mobile" aria-label="Menú de Tony Sportswear" onClose={()=>{setMobileOpen(false);if(!search.current?.open)menuButton.current?.focus();}} onClick={event=>{if(event.target===event.currentTarget)closeMobile();}}><div className="tony-mobile-inner"><div className="tony-mobile-top"><Brand/><button type="button" className="tony-icon-button" aria-label="Cerrar menú" autoFocus onClick={closeMobile}><Icon name="close"/></button></div><button className="tony-mobile-search" type="button" onClick={openSearch}><Icon name="search"/>Busca un producto, una tienda o una idea.</button><div className="tony-mobile-support"><Link href="/carrito" onClick={closeMobile}>Mi carrito <Icon name="diagonal"/></Link><a href="#contactos" onClick={closeMobile}>Contactos <Icon name="diagonal"/></a></div><span className="tony-mega-kicker">TU IDENTIDAD TIENE SU LUGAR.</span><nav aria-label="Navegación principal" className="tony-mobile-nav"><Link href="/" onClick={closeMobile} aria-current={isHome?'page':undefined}><span>01</span>Inicio <Icon name="diagonal"/></Link>{menus.map((menu,index)=><div className="tony-mobile-group" key={menu.id}><button type="button" aria-controls={`tony-mobile-${menu.id}`} aria-expanded={accordion===menu.id} onClick={()=>setAccordion(accordion===menu.id?null:menu.id)}><span>{String(index+2).padStart(2,'0')}</span>{menu.label}<b aria-hidden="true">{accordion===menu.id?'−':'+'}</b></button><div id={`tony-mobile-${menu.id}`} className="tony-mobile-sub" hidden={accordion!==menu.id}>{menu.id==='product'?<><Link href="/producto" onClick={closeMobile}>Explorar Producto <Icon name="arrow"/></Link>{PRODUCT_CATEGORIES.map(category=><Link href={productHref(category)} key={category.id} onClick={closeMobile}>{category.shortLabel}</Link>)}</>:(menu.id==='company'?company:customer).map(([href,label])=><Link href={href} key={href} onClick={closeMobile}>{label}</Link>)}</div></div>)}<Link href="/tony-news" onClick={closeMobile} aria-current={path==='/tony-news'?'page':undefined}><span>05</span>Tony News <Icon name="diagonal"/></Link>{isHome&&<Link href="/configurador" className="tony-mobile-create" onClick={closeMobile}><span>06</span>Crea tu uniforme <Icon name="diagonal"/></Link>}</nav><div className="tony-mobile-signature"><Claw/><span>TU EQUIPO.<br/><strong>TU IDENTIDAD.</strong></span></div></div></dialog>
    <dialog ref={search} className="tony-search" aria-labelledby="tony-search-title" onClose={()=>{setSearchOpen(false);searchButton.current?.focus();}} onClick={event=>{if(event.target===event.currentTarget)closeSearch();}}><div className="tony-search-inner"><div className="tony-search-heading"><span className="tony-mega-kicker">TE AYUDAMOS EN TU BÚSQUEDA</span><button className="tony-icon-button" type="button" aria-label="Cerrar búsqueda" onClick={closeSearch}><Icon name="close"/></button></div><h2 id="tony-search-title">¿QUÉ BUSCAS<br/><em>EN ESPECÍFICO?</em></h2><label htmlFor="site-search" className="sr-only">Buscar una sección</label><div className="tony-search-input"><Icon name="search"/><input ref={searchInput} id="site-search" type="search" autoFocus={searchOpen} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='ArrowDown'){event.preventDefault();search.current?.querySelector<HTMLAnchorElement>('.tony-search-results>a')?.focus();}}} placeholder="Uniformes, fútbol, telas, tiendas…"/>{query&&<button type="button" className="tony-search-clear" aria-label="Limpiar búsqueda" onClick={()=>{setQuery('');searchInput.current?.focus();}}><Icon name="close"/></button>}</div><p className="tony-search-count" data-state={words.length?(results.length?'found':'empty'):'initial'} aria-live="polite">{words.length?`${results.length} ${results.length===1?'resultado encontrado':'resultados encontrados'}`:'TODOS LOS APARTADOS Y FUNCIONES'}</p><div className="tony-search-results">{searchOpen&&(results.length?results.map(item=>{return <Link href={item.href} key={item.href} prefetch={false} onClick={closeSearch} aria-label={item.label}><div><span>{item.group}</span><strong>{item.label}</strong></div><Icon name="diagonal"/></Link>;}):<div className="tony-search-empty"><span className="tony-search-empty-mark" aria-hidden="true"><Icon name="search"/></span><strong>Probemos otra palabra.</strong><p>No hay una sección que coincida con “{query}”. Prueba con una tienda, un producto o un material.</p><button type="button" onClick={()=>{setQuery('');searchInput.current?.focus();}}>Ver puntos de partida <Icon/></button><Link href="/contacto" onClick={closeSearch}>O habla con Tony <Icon/></Link></div>)}</div><p className="tony-search-hint"><kbd>Esc</kbd> para cerrar <span>↓ para explorar resultados</span></p></div></dialog>
  </>;
}
