export type SportLine = {
  id:string; name:string; headline:string; description:string; items:string[];
  color:string; accent:string; kind:'football'|'basketball'|'volleyball'|'running'|'cycling'|'racing'|'polo'|'casual'|'equipment';
  note:string;
};
export const SPORT_LINES:SportLine[] = [
  {id:'futbol',name:'Fútbol',headline:'TU ESCUDO.\nTU CANCHA.',description:'Un equipo se reconoce antes del primer toque. Define los colores, el escudo y la identidad de cada jugador.',items:['Uniformes de equipo','Moldes de fútbol','Nombres y dorsales'],color:'#C3FF53',accent:'#173426',kind:'football',note:'Puedes preparar la cantidad, la nómina y tu diseño en nuestro estudio de uniformes.'},
  {id:'baloncesto',name:'Baloncesto',headline:'HAZTE GRANDE.\nJUEGA EN EQUIPO.',description:'La identidad del club, del calentamiento al último cuarto. Comparte tu idea para definir una propuesta de baloncesto.',items:['Uniformes BKB','Identidad del club','Personalización por jugador'],color:'#F1ECDC',accent:'#D35D36',kind:'basketball',note:'Consulta el corte, las tallas y las piezas que necesita tu equipo.'},
  {id:'voleibol',name:'Voleibol',headline:'CADA PUNTO.\nLA MISMA PASIÓN.',description:'Un mismo lenguaje para todo el equipo. Coordina diseño, colores, nombres y dorsales de tu uniforme.',items:['Uniformes de voleibol','Colores del equipo','Detalles personalizados'],color:'#4A6EE8',accent:'#F0F3E5',kind:'volleyball',note:'Indica la categoría y las prendas que necesitas para recibir una propuesta.'},
  {id:'running',name:'Running',headline:'TU RITMO.\nTU PROPIA HUELLA.',description:'Para el grupo que entrena contigo y los colores que te acompañan a la meta. Cuéntanos cómo corre tu equipo.',items:['Línea runners','Identidad de grupos','Diseño personalizado'],color:'#EF815B',accent:'#243C32',kind:'running',note:'Comparte el uso previsto, la cantidad y el tipo de prenda que buscas.'},
  {id:'ciclismo',name:'Ciclismo',headline:'LA RUTA CAMBIA.\nTU IDENTIDAD NO.',description:'Lleva los colores de tu grupo en cada recorrido. Prepara tus referencias para una propuesta de la línea de ciclismo.',items:['Línea ciclismo','Colores del club','Arte propio'],color:'#DDE3C9',accent:'#3D6D4F',kind:'cycling',note:'Tony te ayudará a confirmar las prendas y opciones disponibles para tu grupo.'},
  {id:'racing',name:'Racing',headline:'ACTITUD\nEN CADA SALIDA.',description:'Una imagen compartida para quienes viven la pista y el equipo. Da forma a tus colores, marcas y patrocinadores.',items:['Línea racing','Identidad de escudería','Patrocinadores y gráficos'],color:'#D75138',accent:'#F1EBDC',kind:'racing',note:'Las propuestas de esta línea se coordinan con Tony según las referencias del equipo.'},
  {id:'empresarial',name:'Empresarial',headline:'TU MARCA\nTAMBIÉN JUEGA.',description:'Tu equipo de trabajo merece una identidad coherente. Define el uso de las prendas, tus colores y la ubicación de la marca.',items:['Línea empresarial','Identidad de marca','Grupos y organizaciones'],color:'#D9E1D2',accent:'#18392E',kind:'polo',note:'Comparte tu logo, la cantidad y el uso de las prendas para confirmar el acabado.'},
  {id:'casual',name:'Camisas y polos',headline:'LA IDENTIDAD\nVA CONTIGO.',description:'Del encuentro con tu grupo a la actividad de tu organización. Explora una propuesta de camisa deportiva o tipo polo.',items:['Camisas deportivas','Camisas tipo polo','Diseño para tu grupo'],color:'#7692B1',accent:'#EDF0DF',kind:'casual',note:'Las opciones de tela, cuello y personalización se definen junto con Tony.'},
  {id:'implementos',name:'Implementos',headline:'EL EQUIPO\nSE COMPLETA.',description:'Consulta los implementos y complementos que necesita tu grupo. Te ayudamos a identificar qué buscar antes de cotizar.',items:['Implementos deportivos','Consulta de disponibilidad','Complementos para el equipo'],color:'#E6DFCD',accent:'#1E4635',kind:'equipment',note:'Indica el deporte, el implemento y la cantidad. La disponibilidad se confirma al consultar.'},
];
export const lineQuote = (line:SportLine) => `https://wa.me/50370155571?text=${encodeURIComponent(`Hola, Tony. Me interesa la línea ${line.name}. Quisiera compartir mi idea y confirmar las opciones, la cantidad y los detalles de una cotización.`)}`;
