'use client';
import dynamic from 'next/dynamic';
import {useEffect, useRef, useState, type Dispatch, type SetStateAction} from 'react';
import {money} from '@/lib/pedido/pricing';
import type {Buyer, Delivery, Payment, PedidoErrors, PedidoPricing} from '@/lib/pedido/types';
import checkout from '@/data/pedido/checkout.json';
import {Choice, Field} from './PedidoUI';
const SignaturePad = dynamic(() => import('./SignaturePad'), {ssr: false});
const DeliveryMap = dynamic(() => import('./DeliveryMap'), {ssr: false, loading: () => <p role="status">Abriendo el mapa…</p>});
const DEPARTMENTS = ['Ahuachapán', 'Cabañas', 'Chalatenango', 'Cuscatlán', 'La Libertad', 'La Paz', 'La Unión', 'Morazán', 'San Miguel', 'San Salvador', 'San Vicente', 'Santa Ana', 'Sonsonate', 'Usulután'];
interface Props {
  step: number; disabled?: boolean; delivery: Delivery; setDelivery: Dispatch<SetStateAction<Delivery>>;
  payment: Payment; setPayment: Dispatch<SetStateAction<Payment>>; buyer: Buyer; setBuyer: Dispatch<SetStateAction<Buyer>>;
  signature: string; setSignature: (value: string) => void; terms: boolean; setTerms: (value: boolean) => void;
  errors: PedidoErrors; pricing: PedidoPricing; verified: boolean; paymentUrl: string;
  startPayment: () => Promise<void>; checkPayment: () => Promise<void>; uploadReceipt: (file?: File) => Promise<void>;
  onFailure: (value: string) => void; onNotice: (value: string) => void;
}
export default function CheckoutSteps({step, disabled, delivery, setDelivery, payment, setPayment, buyer, setBuyer, signature, setSignature, terms, setTerms, errors, pricing, verified, paymentUrl, startPayment, checkPayment, uploadReceipt, onFailure, onNotice}: Props) {
  const [showMap, setShowMap] = useState(false), [locating, setLocating] = useState(false);
  const live = useRef(true), currentStep = useRef(step);
  currentStep.current = step;
  useEffect(() => {live.current = true; return () => {live.current = false;};}, []);
  useEffect(() => {if (step !== 10) setLocating(false);}, [step]);
  function locate() {
    if (!navigator.geolocation) {onFailure('Tu navegador no admite ubicación. Puedes seleccionarla en el mapa.'); return;}
    setLocating(true); navigator.geolocation.getCurrentPosition(position => {if (!live.current || currentStep.current !== 10) return; setDelivery(previous => ({...previous, latitude: position.coords.latitude, longitude: position.coords.longitude})); setShowMap(true); setLocating(false); onNotice('Ubicación seleccionada. Confirma la dirección exacta.');}, () => {if (!live.current || currentStep.current !== 10) return; setLocating(false); onFailure('No pudimos obtener tu ubicación. Puedes elegirla en el mapa o escribir la dirección.');}, {timeout: 12000, maximumAge: 60000});
  }
  if (step === 10) return <div><div className="pedido-options two"><Choice selected={delivery.kind === 'pickup'} onClick={() => setDelivery({...delivery, kind: 'pickup'})}><strong>Retiro en tienda</strong><span>$0.00</span></Choice><Choice selected={delivery.kind === 'home'} onClick={() => setDelivery({...delivery, kind: 'home'})}><strong>Envío a domicilio</strong><span>+$6.00</span></Choice></div>{delivery.kind === 'pickup' && <Field label="Sucursal para retirar" error={errors['delivery.branch']}><select value={delivery.branch} onChange={e => setDelivery({...delivery, branch: e.target.value})}><option value="">Elige tu sucursal</option>{checkout.branches.map(branch => <option key={branch}>{branch}</option>)}</select></Field>}{delivery.kind === 'home' && <div className="pedido-delivery-fields"><Field label="Departamento" error={errors['delivery.department']}><select value={delivery.department} onChange={e => setDelivery({...delivery, department: e.target.value})}><option value="">Selecciona departamento</option>{DEPARTMENTS.map(department => <option key={department}>{department}</option>)}</select></Field><Field label="Municipio o distrito" error={errors['delivery.city']}><input value={delivery.city} maxLength={100} onChange={e => setDelivery({...delivery, city: e.target.value})}/></Field><Field label="Dirección exacta" error={errors['delivery.address']}><textarea value={delivery.address} maxLength={300} onChange={e => setDelivery({...delivery, address: e.target.value})}/></Field><Field label="Punto de referencia"><input value={delivery.reference} maxLength={200} onChange={e => setDelivery({...delivery, reference: e.target.value})}/></Field><div className="pedido-inline-actions"><button type="button" className="button outline" disabled={locating} onClick={locate}>{locating ? 'Localizando…' : 'Usar mi ubicación'}</button><button type="button" className="button outline" onClick={() => setShowMap(true)}>Elegir en el mapa</button></div>{showMap && <DeliveryMap latitude={delivery.latitude} longitude={delivery.longitude} onChange={(latitude, longitude) => setDelivery(previous => ({...previous, latitude, longitude}))}/>}<div className="pedido-inline-fields"><Field label="Latitud (opcional)"><input inputMode="decimal" type="number" step="any" value={delivery.latitude ?? ''} onChange={e => setDelivery({...delivery, latitude: e.target.value === '' ? null : Number(e.target.value)})}/></Field><Field label="Longitud (opcional)"><input inputMode="decimal" type="number" step="any" value={delivery.longitude ?? ''} onChange={e => setDelivery({...delivery, longitude: e.target.value === '' ? null : Number(e.target.value)})}/></Field></div></div>}</div>;
  if (step === 11) return <div><div className="pedido-deposit"><span>ANTICIPO DEL 50 %</span><strong>{money(pricing.depositCents)}</strong><p>Saldo contra entrega: {money(pricing.balanceCents)}</p></div><div className="pedido-options two"><Choice selected={payment.method === 'wompi'} disabled={verified} onClick={() => setPayment({...payment, method: 'wompi'})}><strong>Wompi</strong><span>Tarjeta · pago seguro</span></Choice><Choice selected={payment.method === 'transfer'} disabled={verified} onClick={() => setPayment({...payment, method: 'transfer'})}><strong>Transferencia bancaria</strong><span>Adjunta tu comprobante</span></Choice></div>{payment.method === 'wompi' && <div className="pedido-payment-box"><p>QuickPay y Nequi aparecerán en Wompi si están habilitados para el comercio. El pedido continúa cuando el anticipo esté verificado.</p>{!verified && <button className="button primary" type="button" onClick={() => void startPayment()}>{paymentUrl ? 'Recuperar enlace de pago' : 'Preparar pago del anticipo'}</button>}{paymentUrl && !verified && <a className="button outline" href={paymentUrl}>Abrir pago seguro ↗</a>}{payment.reference && <><p>Referencia: <strong>{payment.reference}</strong></p><button className="button outline" type="button" onClick={() => void checkPayment()}>Verificar mi anticipo</button></>}{verified && <p className="pedido-notice">✓ Anticipo verificado</p>}</div>}{payment.method === 'transfer' && <div className="pedido-payment-box"><Field label="Banco de la transferencia" error={errors['payment.bank']}><select value={payment.bank} onChange={e => setPayment({...payment, bank: e.target.value})}><option value="">Selecciona un banco</option>{checkout.banks.map(bank => <option key={bank.bank}>{bank.bank}</option>)}</select></Field>{checkout.banks.filter(bank => bank.bank === payment.bank).map(bank => <div className="pedido-bank" key={bank.bank}><strong>{bank.bank}</strong><p>{bank.label}</p><p>{bank.holder}</p></div>)}<Field label="Comprobante de transferencia (PNG, JPG o WebP, máximo 4 MB)" error={errors['payment.receiptData']}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => void uploadReceipt(e.target.files?.[0])}/></Field>{payment.receiptName && <p className="pedido-notice">✓ {payment.receiptName}</p>}<p className="pedido-fine">La transferencia quedará en revisión hasta que Tony confirme el depósito.</p></div>}</div>;
  return <div><p>Datos de la persona responsable del pedido. Se enviarán por conexión segura al confirmar; no se guardan en el navegador.</p><div className="pedido-buyer"><Field label="Nombre completo" error={errors['buyer.name']}><input autoComplete="name" value={buyer.name} maxLength={100} onChange={e => setBuyer({...buyer, name: e.target.value})}/></Field><Field label="DUI (00000000-0)" error={errors['buyer.dui']}><input value={buyer.dui} maxLength={10} inputMode="numeric" onChange={e => setBuyer({...buyer, dui: e.target.value})}/></Field><Field label="WhatsApp" error={errors['buyer.phone']}><input type="tel" autoComplete="tel" value={buyer.phone} maxLength={20} onChange={e => setBuyer({...buyer, phone: e.target.value})}/></Field><Field label="Correo electrónico (opcional)" error={errors['buyer.email']}><input type="email" autoComplete="email" value={buyer.email} maxLength={100} onChange={e => setBuyer({...buyer, email: e.target.value})}/></Field></div><details className="pedido-details" open><summary>Términos y condiciones · 13 puntos</summary><ol className="pedido-terms">{checkout.terms.map((term, i) => <li key={i}>{term.replace(/^\d+[.)]\s*/, '')}</li>)}</ol></details><label className="pedido-check"><input type="checkbox" checked={terms} onChange={e => setTerms(e.target.checked)}/> Leí y acepto los términos y condiciones del pedido.</label><SignaturePad value={signature} onChange={setSignature} disabled={disabled}/></div>;
}
