import SectionImage from '@/components/SectionImage';
import type { Metadata } from 'next';
import { EditorialShell, EditorialHero, EditorialLink, SectionLabel } from '@/components/TonyEditorial';
export const metadata: Metadata = {title:'Comunidad, App Tony y TonyPlay',description:'Conoce la App Tony, el futuro juego TonyPlay y los proyectos que conectan a la comunidad de Tony.'};
export default function CommunityPage() {
  return <EditorialShell className="te-community"><EditorialHero label="Comunidad" eyebrow="LA IDENTIDAD SE COMPARTE" title={<>Compartimos<br /><em>la cancha.</em></>} description="El deporte reúne equipos, personas e ideas. Encuentra aquí los canales de Tony para seguir conectado, conocer sus publicaciones y proponer una colaboración." />
    <section className="te-cream" id="app-tony"><div className="te-wrap"><SectionLabel number="01">La App Tony</SectionLabel><div className="te-app-layout"><div><h2>Tu vínculo con Tony.<br /><em>También en tu teléfono.</em></h2><p className="te-body-copy" style={{color:'#4a643e',marginTop:24}}>Las fichas de la aplicación describen un código de cliente, consulta de puntos, recompensas e historial. Revisa en la app las condiciones que correspondan a tu cuenta.</p><div className="te-app-features">{[{n:'01',title:'Código de cliente',text:'Una identificación para tu relación con Tony.'},{n:'02',title:'Saldo de puntos',text:'Consulta el saldo disponible en tu cuenta.'},{n:'03',title:'Recompensas',text:'Explora lo que la app presenta para sus clientes.'},{n:'04',title:'Tu historial',text:'Revisa el registro de puntos y canjes.'}].map(item => <div key={item.n}><span>{item.n}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></div>)}</div><div className="te-actions"><EditorialLink href="https://play.google.com/store/apps/details?id=com.tonysports.customer" external>Google Play</EditorialLink><EditorialLink href="https://apps.apple.com/us/app/tony/id1528399939" external outline>App Store</EditorialLink></div></div><div className="te-app-poster"><SectionImage photo="app-tony" shade="left" /><span className="te-app-poster-top">TONY / EN TU TELÉFONO</span><div className="te-phone"><span className="te-phone-word">TONY<small>SPORTSWEAR</small></span><strong>TU EQUIPO.<br />TU HISTORIA.</strong><div className="te-phone-menu"><span>Código de cliente <i>↗</i></span><span>Puntos y recompensas <i>↗</i></span><span>Historial <i>↗</i></span></div><span className="te-phone-note">ILUSTRACIÓN DE FUNCIONES</span></div></div></div><p className="te-source" style={{color:'#4d6a3e'}}>Funciones descritas en las fichas de las tiendas de aplicaciones. <a style={{color:'#315626'}} href="https://www.tonysportselsalvador.com/app-tony/" target="_blank" rel="noopener noreferrer">Conocer la App Tony en su publicación oficial ↗</a></p></div></section>
    <section className="te-wrap te-tonyplay" id="tonyplay" aria-labelledby="te-tonyplay-title"><div className="te-tonyplay-copy"><SectionLabel number="02">TonyPlay</SectionLabel><p className="te-project-status"><span aria-hidden="true" />EN DESARROLLO</p><h2 id="te-tonyplay-title">Otra forma<br /><em>de jugar.</em></h2><p>Estamos desarrollando <strong>TonyPlay</strong>, el futuro juego de Tony. Una nueva parte de nuestro universo, además de la App Tony.</p><p>Aquí compartiremos sus novedades cuando estén listas.</p></div><div className="te-tonyplay-art" aria-hidden="true"><span className="te-tonyplay-word">TONY<span>PLAY</span></span><SectionImage photo="tonyplay" fit="contain" position="center" /><span className="te-tonyplay-art-note">EL PRÓXIMO CAPÍTULO ESTÁ EN CAMINO.</span></div></section>
    <section className="te-wrap"><SectionLabel number="03">Responsabilidad social</SectionLabel><div className="te-featured-story"><div className="te-story-art" aria-hidden="true"><SectionImage photo="comunidad" /><span>MÁS ALLÁ<br />DE LA<br />CANCHA.</span></div><div className="te-story-copy"><h2>La comunidad<br /><em>también se cuenta.</em></h2><p>Tony mantiene una galería de Responsabilidad Social Empresarial. Puedes conocer ese registro visual directamente en su publicación.</p><p>Para conversar sobre una iniciativa de tu club, academia o comunidad, prepara una propuesta con el lugar, los participantes y lo que buscan construir.</p><div className="te-actions"><EditorialLink href="https://www.tonysportselsalvador.com/producto/responsabilidad-social-empresarial/" external>Ver la galería de Tony</EditorialLink><EditorialLink href="/patrocinio#propuesta" outline>Presentar una iniciativa</EditorialLink></div></div></div></section>
    <section className="te-cream"><div className="te-wrap"><SectionLabel number="04">Lo que nos reúne</SectionLabel><h2>Una misma camiseta.<br /><em>Muchas formas de sumar.</em></h2><div className="te-community-values"><article><h3>Tu equipo.</h3><p>Organiza a tus integrantes, comparte la idea y construyan juntos una identidad que los represente.</p></article><article><h3>Tu proyecto.</h3><p>Si tienes una iniciativa deportiva, explica su propósito y sus necesidades. Una propuesta clara permite iniciar la conversación.</p></article><article><h3>Tu próximo paso.</h3><p>Conoce las líneas, prepara un pedido o acércate a una tienda para conversar sobre lo que necesitas.</p></article></div></div></section>
  </EditorialShell>;
}
