import type { Metadata } from 'next';
import { SponsorshipProposal } from '@/components/EditorialTools';
import { EditorialShell, EditorialHero, SectionLabel, SourceNote } from '@/components/TonyEditorial';
export const metadata: Metadata = {title:'Patrocinio y propuestas de colaboración',description:'Presenta tu club, academia o proyecto deportivo a Tony. Prepara y revisa una propuesta antes de compartirla por WhatsApp o correo.'};
export default function SponsorshipPage() {
  return <EditorialShell className="te-sponsorship"><EditorialHero label="Patrocinio" eyebrow="LAS GRANDES IDEAS JUEGAN EN EQUIPO" title={<>Una propuesta.<br /><em>Muchas ganas de jugar.</em></>} description="Cuéntanos quiénes son, qué están construyendo y cómo imaginan una colaboración con Tony. Una conversación bien preparada es el primer paso." aside={<div className="te-sponsorship-emblem"><span aria-hidden="true" /><strong>TU CLUB.<br /><em>TU VOZ.</em></strong></div>} />
    <section className="te-band"><div className="te-wrap te-band-inner"><strong>El talento también necesita una identidad.</strong><p>Presenta una propuesta concreta. Compartirla no implica aprobación de patrocinio ni compromisos económicos.</p></div></section>
    <section className="te-wrap"><SectionLabel number="01">Equipos que Tony presenta</SectionLabel><div className="te-section-heading"><h2>El fútbol forma parte<br /><em>de esta historia.</em></h2><p>En su página de patrocinadores, Tony muestra a estos clubes. La publicación no indica una temporada de vigencia.</p></div><div className="te-club-names">{['C.D. Dragón','C.D. Platense','C.D. Cacahuatique','C.F. Marte Soyapango'].map((club,index) => <div key={club}><span>0{index+1}</span><h3>{club}</h3></div>)}</div><SourceNote href="https://www.tonysportselsalvador.com/patrocinadores/">Equipos mencionados en la publicación de patrocinadores de Tony.</SourceNote></section>
    <section className="te-wrap te-rule" id="propuesta"><div className="te-proposal-layout"><aside className="te-proposal-aside"><SectionLabel number="02">Tu siguiente conversación</SectionLabel><h2>Una buena propuesta<br /><em>se entiende desde el inicio.</em></h2><p>Clubes, academias y organizaciones pueden usar este espacio para preparar su presentación.</p><ol className="te-proposal-points"><li><span>01</span>Explica quiénes son y en qué categoría participan.</li><li><span>02</span>Cuenta qué necesitan y qué les gustaría aportar a una colaboración.</li><li><span>03</span>Incluye a la persona responsable para continuar la conversación.</li></ol></aside><SponsorshipProposal /></div></section>
  </EditorialShell>;
}
