import type { Metadata } from 'next';
import { EditorialShell, EditorialHero, EditorialLink, SectionLabel } from '@/components/TonyEditorial';
export const metadata: Metadata = {title:'Actualidad y guías para tu equipo',description:'Prepara tus archivos, organiza la nómina y revisa los detalles de tu uniforme con las guías de Tony.'};
export default function NewsPage() {
  return <EditorialShell className="te-news"><EditorialHero label="Actualidad" eyebrow="IDEAS QUE TAMBIÉN SE LLEVAN A LA CANCHA" title={<>Tu equipo.<br /><em>El siguiente capítulo.</em></>} description="Guías para preparar tus archivos, organizar a tu equipo y revisar los detalles con más claridad." />
    <section className="te-wrap te-rule" style={{paddingTop:0,borderTop:0}}><article className="te-news-feature"><div className="te-news-poster" aria-hidden="true"><span>UN NUEVO<br />CAPÍTULO.<br />MISMA GARRA.</span></div><div className="te-news-feature-copy"><p className="te-eyebrow">CATÁLOGO / PRÓXIMAMENTE</p><h2>El nuevo catálogo<br />tendrá su lugar aquí.</h2><p>El catálogo actualizado sigue pendiente. Mientras llega, puedes explorar las líneas de Tony y preparar una propuesta para el uniforme de tu equipo.</p><EditorialLink href="/lineas">Explorar las líneas</EditorialLink></div></article></section>
    <section className="te-wrap" id="guias"><div className="te-guides"><div><SectionLabel number="01">Guías para tu pedido</SectionLabel><h2>Prepararlo bien<br /><em>hace la diferencia.</em></h2><p>Tres lecturas breves para llegar a tu conversación con el equipo de diseño con menos dudas y una propuesta más clara.</p></div><div className="te-accordion"><details open><summary><span><span className="te-guide-label">GUÍA 01 / ARCHIVOS</span>Cómo preparar tu escudo y tus imágenes</span></summary><div className="te-guide-content"><p>Una imagen legible ayuda a comunicar la idea y a revisar los detalles.</p><ol><li>Busca el archivo original del escudo o la marca. Si tiene fondo transparente, consérvalo.</li><li>Para probarlo en el editor, usa PNG, JPG o WebP de hasta 4 MB. Evita capturas borrosas cuando tengas el original.</li><li>Sube el diseño y el escudo por separado para poder ubicarlos en la camisa.</li><li>Descarga la vista de frente y de espalda si las necesitas. Al conversar con Tony, adjunta los bocetos y los originales.</li></ol><p style={{marginTop:18}}>El PNG del editor es orientativo. El arte de producción se revisa con Tony.</p></div></details><details><summary><span><span className="te-guide-label">GUÍA 02 / NÓMINA</span>Una lista de jugadores que evita confusiones</span></summary><div className="te-guide-content"><ol><li>Define primero cuántos uniformes necesitas. Incluye a los porteros en esa cantidad.</li><li>Escribe el nombre o apellido tal como irá en la prenda y revisa los acentos.</li><li>Confirma una talla y un dorsal por integrante. Si repites un dorsal, comprueba que sea intencional.</li><li>Pide a cada persona que revise sus datos antes de compartir la nómina.</li><li>Conserva el resumen del pedido y el archivo de la lista para la revisión final.</li></ol></div></details><details><summary><span><span className="te-guide-label">GUÍA 03 / APROBACIÓN</span>Qué revisar antes de dar el visto bueno</span></summary><div className="te-guide-content"><ol><li>Vista del frente y de la espalda: color base, gráficos, escudo y patrocinadores.</li><li>Ortografía, nombres y dorsales de toda la nómina.</li><li>Tallas, molde, cuello, manga y la línea de prenda acordada.</li><li>Técnica y acabados que Tony confirme para esa combinación.</li><li>Cotización, condiciones y coordinación de la entrega.</li></ol><p style={{marginTop:18}}>Si falta una confirmación, aclárala con el asesor antes de autorizar la producción.</p></div></details></div></div></section>
  </EditorialShell>;
}
